# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:latest
    volumes:
      - C:\mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: pool
      MYSQL_USER: admin
      MYSQL_PASSWORD: 'X6ZS3VQ48$ZhW'
